package rules

import com.sbnz.model.indicators.ExhaustionIndicator;
import com.sbnz.model.indicators.CynicismIndicator;
import com.sbnz.model.indicators.ReducedEfficacyIndicator;
import com.sbnz.model.risks.DominantDimension;

rule "Create dominant dimension all three"
salience 60
when
    ExhaustionIndicator($sid : studentId)
    CynicismIndicator(studentId == $sid)
    ReducedEfficacyIndicator(studentId == $sid)
    not DominantDimension(studentId == $sid)
then
    insert(new DominantDimension(
        $sid,
        "kombinovani obrazac: akademska iscrpljenost, cinizam/distanca i smanjena akademska efikasnost"
    ));
end

rule "Upgrade dominant dimension to all three"
salience 59
when
    ExhaustionIndicator($sid : studentId)
    CynicismIndicator(studentId == $sid)
    ReducedEfficacyIndicator(studentId == $sid)
    $d : DominantDimension(studentId == $sid,
        value != "kombinovani obrazac: akademska iscrpljenost, cinizam/distanca i smanjena akademska efikasnost")
then
    modify($d) {
        setValue("kombinovani obrazac: akademska iscrpljenost, cinizam/distanca i smanjena akademska efikasnost")
    }
end

rule "Dominant dimension exhaustion and efficacy"
salience 40
when
    ExhaustionIndicator($sid : studentId)
    ReducedEfficacyIndicator(studentId == $sid)
    not CynicismIndicator(studentId == $sid)
    not DominantDimension(studentId == $sid)
then
    insert(new DominantDimension(
        $sid,
        "akademska iscrpljenost i smanjena akademska efikasnost"
    ));
end

rule "Dominant dimension exhaustion and cynicism"
salience 40
when
    ExhaustionIndicator($sid : studentId)
    CynicismIndicator(studentId == $sid)
    not ReducedEfficacyIndicator(studentId == $sid)
    not DominantDimension(studentId == $sid)
then
    insert(new DominantDimension(
        $sid,
        "akademska iscrpljenost i cinizam/distanca prema studijama"
    ));
end

rule "Dominant dimension cynicism and efficacy"
salience 40
when
    CynicismIndicator($sid : studentId)
    ReducedEfficacyIndicator(studentId == $sid)
    not ExhaustionIndicator(studentId == $sid)
    not DominantDimension(studentId == $sid)
then
    insert(new DominantDimension(
        $sid,
        "cinizam/distanca prema studijama i smanjena akademska efikasnost"
    ));
end
